@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title Linux Admin Assistant

* <&star>OS_DETECT
* <&star>USR_VERIFY
* <&star>INSTALLER
* <&flag>$GREET+Query?
** <&globe>
*** Option 1
*** Option 2
*** Option 3
*** Option 4
** <&graph>
** <&pulse>
** <&people>
** <&star>Repair. Options
*** <s></s> => ?
*** <s></s> => ?

header
mindMap
endheader

center footer My super footer

legend left
  legend
  <&star>=
  <&flag>=
  <&globe>=OS
  <&graph>=Report
  <&pulse>=Update
  <&people>=User/Home
endlegend
@endmindmap
